name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
          java-version: 8
    - name: Checkout
      uses: actions/checkout@v3
      
    # Set Up The Java 
    - name: Setup JDK 1.8
      uses: actions/checkout@v3
      with:
        java-version: 1.8  
    - name: Build Code
      run: mvn -B package --file pom.xml
    - name: Sonar Scanner
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rishikant4_github_actions
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: /home/runner/work/github_actions/github_actions/target/simple-app-2.0.0
        
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: rishi236/rishiapps
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
