name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: windows-latest
    
    #strategy:
     # matrix:
       # os: [ubuntu-lates ,windows-latest]
        
    #container:
     # image: node:14.16
      #env:
       # NODE_ENV: development
     # ports:
      #  - 80
      #volumes:
      #  - my_docker_volume:/volume_mount
      #options: --cpus 1
    steps:
    - name: Run Windows conatiner
      run: docker run --rm mcr.microsoft.com/windows/servercore/insider:10.0.20348.1 cmd /c echo "Hello from Windows Conatiner"
      

      
    # Set Up The Java 
    - name: Setup JDK 1.8
      uses: actions/checkout@v3
      with:
        java-version: 1.8  
        
        
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin' 
       java-version: '11'
        
    - name: Build Code
      run: mvn -B package --file pom.xml
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: /home/runner/work/github_actions/github_actions/target/simple-app-2.0.0
        
  Docker:
    needs: [ container-test-job]
    runs-on: ubuntu-latest   
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Code
      run: mvn -B package --file pom.xml
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rishiapps:latest
        
        
  Deploy:
    needs: Docker
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.GKE_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
        CLUSTER_NAME: github-actions-gke
        ZONE_NAME: us-central1-c
      with:
        args: apply -f deployment.yaml
